<?php
header('Content-type: text/plain');
?>

# Kickstart file automatically generated by anaconda.

#version=DEVEL
install
cdrom
lang en_US.UTF-8
keyboard us
network     --onboot yes --device eth0 --bootproto dhcp
rootpw      --iscrypted $6$BtLQAX.Fd0GY92Kd$DQ/pvulr.ai/f6vFsFlwGHiVLwEt0cpG6bCmKkRcYoX0DrhFKAycF8STkQt.66YwZELfzF2i/r/utLeNlaWhG0
firewall    --disabled
authconfig  --enableshadow --passalgo=sha512
selinux     --permissive
firstboot   --disabled
timezone    --utc America/Los_Angeles
bootloader  --location=mbr --driveorder=sda --append=" crashkernel=auto vga=0x317"
#  reboot

# -----------------------------------------------------------------------------------------------------
%pre --interpreter=bash

parted -s           /dev/sda            mktable gpt

[ -b                /dev/sda1 ] &&      parted /dev/sda         rm 1    ||  echo "INFO: No partition named /dev/sda1"
parted -s           /dev/sda            mkpart      h2001-boot          3MB     1GB
mkfs.ext4           /dev/sda1   -m 1    -L          h2001-boot  -F -F   -E discard
sleep 5

[ -b                /dev/sda2 ] &&      parted /dev/sda         rm 2    ||  echo "INFO: No partition named /dev/sda2"
parted -s           /dev/sda            mkpart      h2001-os03          1GB     50GB
mkfs.ext4           /dev/sda2   -m 1    -L          h2001-os03  -F -F   -E discard
sleep 5

[ -b                /dev/sda3 ] &&      parted /dev/sda         rm 3    ||  echo "INFO: No partition named /dev/sda3"
parted -s           /dev/sda            mkpart      h2001-os04          50GB    100GB
mkfs.ext4           /dev/sda3   -m 1    -L          h2001-os04  -F -F   -E discard
sleep 5

%end

# -----------------------------------------------------------------------------------------------------

part    /boot                   --fstype=ext4   --onpart=LABEL=h2001-boot --noformat
part    /                       --fstype=ext4   --onpart=LABEL=h2001-os03 --noformat
part    /mnt/h2001/os04         --fstype=ext4   --onpart=LABEL=h2001-os04 --noformat


%packages

@base
@core
@system-admin-tools
# @additional-devel
# @client-mgmt-tools
# @console-internet
# @debugging
# @basic-desktop
# @desktop-debugging
# @desktop-platform
# @desktop-platform-devel
# @development
# @directory-client
# @eclipse
# @emacs
# @storage-client-fcoe
# @ftp-server
# @fonts
# @general-desktop
# @graphical-admin-tools
# @graphics
# @hardware-monitoring
# @ha-management
# @input-methods
# @internet-applications
# @internet-browser
# @java-platform
# @kde-desktop
# @large-systems
# @legacy-x
# @mysql
# @nfs-file-server
# @network-file-system-client
# @network-tools
# @office-suite
# @php
# @performance
# @perl-runtime
# @postgresql-client
# @postgresql
# @print-client
# @remote-desktop-clients
# @resilient-storage
# @ruby-runtime
# @scientific
# @security-tools
# @server-platform
# @server-platform-devel
# @server-policy
# @storage-client-multipath
# @tex
# @technical-writing
# @virtualization
# @virtualization-client
# @virtualization-platform
# @virtualization-tools
# @web-server
# @x11
# @storage-client-iscsi
# libXinerama-devel
# openmotif-devel
# libXmu-devel
# xorg-x11-proto-devel
# startup-notification-devel
# libgnomeui-devel
# libbonobo-devel
# junit
# libXau-devel
# libgcrypt-devel
# popt-devel
# libdrm-devel
# libXrandr-devel
# libxslt-devel
# libglade2-devel
# gnutls-devel
# mtools
# pax
# oddjob
# sgpio
# genisoimage
# wodim
# vios-proxy
# abrt-gui
# qt-mysql
# desktop-file-utils
# ant
# rpmdevtools
# jpackage-utils
# rpmlint
# certmonger
# pam_krb5
# krb5-workstation
# gnome-pilot
# netpbm-progs
# ImageMagick
# openmotif
# xterm
# xorg-x11-xdm
# libXmu
# libXp
# ebtables
# sg3_utils
# perl-DBD-SQLite
# rdesktop
# numpy
# atlas
# hmaccalc
# pexpect
# crypto-utils
# scrub
# vios-proxy
# qemu-kvm-tools
# libvirt-snmp
# fence-virtd-serial
# fence-virtd-multicast
# libvirt-java
# libvirt-cim
# fence-virtd-libvirt
# libvirt-qmf
# perl-Sys-Virt
# libguestfs-java
# virt-v2v
# libguestfs-tools
# libguestfs-mount
# certmonger
# perl-CGI
%end

 
